name: test all package installation

run-name: ${{ github.actor }} is learning GitHub Actions


on: [push]




jobs:

  check-package-manager:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          node-version: '20'
      - run: npm install
      - run: yarn lint
